"use strict";
const fs=require("fs"),path=require("path"),crypto=require("crypto"),os=require("os"),{spawn}=require("child_process");
const rt=require("./runtime-config");
const HOUR=60*60*1000;
const SECRET_KEYS=/(access[_ -]?token|refresh[_ -]?token|client[_ -]?secret|smtp(pass(word)?)?|password|cookie|authorization|bearer|code_verifier|oauth.?code|session|private.?key)/i;
const SECRET_VALUE=/(eyJ[a-z0-9_-]{10,}|AIza[0-9A-Za-z_-]{20,}|ya29\.[0-9A-Za-z_-]+|Bearer\s+[A-Za-z0-9._-]+)/ig;
function redact(value,key=""){
 if(SECRET_KEYS.test(key))return "[REDACTED]";
 if(Array.isArray(value))return value.map(v=>redact(v,key));
 if(value&&typeof value==="object"){const out={};for(const [k,v] of Object.entries(value))out[k]=redact(v,k);return out;}
 return typeof value==="string"?value.replace(SECRET_VALUE,"[REDACTED]").replace(/(?:access[_ -]?token|refresh[_ -]?token|client[_ -]?secret|token|secret|password|cookie|authorization|bearer|code_verifier|oauth.?code)\s*[:=]\s*[^\s,;]+/ig,"$1=[REDACTED]").slice(0,5000):value;
}
function safeMessage(value){return String(value||"Erreur inconnue.").replace(SECRET_VALUE,"[REDACTED]").replace(/(?:access[_ -]?token|refresh[_ -]?token|client[_ -]?secret|token|secret|password|cookie|authorization|bearer|code_verifier|oauth.?code)\s*[:=]\s*[^\s,;]+/ig,"$1=[REDACTED]").slice(0,1000);}
function normalize(value){return safeMessage(value).toLowerCase().replace(/\d+/g,"#").replace(/\s+/g," ").trim();}
function hash(value){return crypto.createHash("sha256").update(String(value)).digest("hex");}
function readText(file,limit=12000){try{const text=fs.readFileSync(file,"utf8");return text.split(/\r?\n/).slice(-limit).join("\n");}catch{return "";}}
function readJsonFile(file){try{return JSON.parse(fs.readFileSync(file,"utf8").replace(/^\uFEFF/,""));}catch{return null;}}
function lockState(){const names=["sync.lock","update.lock"];const result={};for(const name of names){const file=rt.dataPath(name);if(!fs.existsSync(file)){result[name]={present:false};continue;}const raw=readText(file,20);let parsed=null;try{parsed=JSON.parse(raw)}catch{}result[name]={present:true,metadata:parsed?redact(parsed):{raw:"[REDACTED_LOCK_CONTENT]"}};}return result;}
function connectionState(){return {googleTokenPresent:rt.hasSecret("google-token"),agattProfilePresent:fs.existsSync(rt.profile("agatt")),dendreoProfilePresent:fs.existsSync(rt.profile("dendreo"))};}
function config(){return readJsonFile(path.join(rt.root,"diagnostic-config.json"))||{};}
function installationId(){return hash(os.hostname()).slice(0,16);}
function crc32(buf){let c=0xffffffff;for(const b of buf){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function u16(n){const b=Buffer.alloc(2);b.writeUInt16LE(n&0xffff);return b;}
function u32(n){const b=Buffer.alloc(4);b.writeUInt32LE(n>>>0);return b;}
function zipFiles(files,target){const locals=[],central=[];let offset=0;for(const file of files){const name=Buffer.from(file.name,"utf8"),raw=Buffer.isBuffer(file.data)?file.data:Buffer.from(String(file.data),"utf8"),body=require("zlib").deflateRawSync(raw),crc=crc32(raw);const local=Buffer.concat([Buffer.from([0x50,0x4b,0x03,0x04]),u16(20),u16(0),u16(8),u16(0),u16(0),u32(crc),u32(body.length),u32(raw.length),u16(name.length),u16(0),name,body]);locals.push(local);const entry=Buffer.concat([Buffer.from([0x50,0x4b,0x01,0x02]),u16(20),u16(20),u16(0),u16(8),u16(0),u16(0),u32(crc),u32(body.length),u32(raw.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]);central.push(entry);offset+=local.length;}const dir=Buffer.concat(central),out=Buffer.concat([...locals,dir,Buffer.from([0x50,0x4b,0x05,0x06]),Buffer.alloc(6),u16(files.length),u16(files.length),u32(dir.length),u32(offset),u16(0)]);fs.writeFileSync(target,out);}
function filesForReport(report){const app=rt.readProgramJson("app-version.json",{}),files=[{name:"report.json",data:JSON.stringify(redact(report),null,2)+"\n"},{name:"app-version.json",data:JSON.stringify(app,null,2)+"\n"},{name:"assistant-planning.log.tail.txt",data:safeMessage(readText(rt.dataPath("assistant-planning.log")))},{name:"connection-state.json",data:JSON.stringify(connectionState(),null,2)+"\n"},{name:"locks.json",data:JSON.stringify(lockState(),null,2)+"\n"},{name:"system.json",data:JSON.stringify({platform:process.platform,release:os.release(),version:os.version(),arch:process.arch,node:process.version,installationId:installationId()},null,2)+"\n"}];const progress=readJsonFile(rt.dataPath("sync-progress.json"));if(progress)files.push({name:"last-progress.json",data:JSON.stringify(redact(progress),null,2)+"\n"});return files;}
function throttleFile(){return rt.dataPath("diagnostics-throttle.json");}
function readThrottle(){return readJsonFile(throttleFile())||{};}
function writeThrottle(value){try{rt.writeJson("diagnostics-throttle.json",value)}catch{}}
function spawnWorker(){if(process.env.SDIS_DIAGNOSTIC_NO_WORKER)return;try{const node=path.join(rt.root,"runtime","node","node.exe");const child=spawn(node,[path.join(rt.root,"diagnostic-worker.js"),"--once"],{cwd:rt.root,detached:true,windowsHide:true,stdio:"ignore"});child.unref();}catch{}}
function shouldReport(message,kind){const text=String(message||"").toLowerCase();if(kind==="user-action")return false;if(/reconnexion n[ée]cessaire|autorisation gmail requise|service temporairement inaccessible|fen[êe]tre.*ferm|annul[ée]e|aucun compte google|synchronisation en cours|mise [àa] jour en cours|aucune mise [àa] jour/.test(text))return false;return true;}
function reportError(input={}){try{rt.initialize();const message=safeMessage(input.error||input.message||"Erreur inconnue.");if(!shouldReport(message,input.kind))return {sent:false,ignored:true};const info=rt.readProgramJson("app-version.json",{}),module=String(input.module||"application"),phase=String(input.phase||"inconnue"),action=String(input.action||"inconnue"),type=String(input.type||input.errorName||"Error"),signature=hash([info.version,module,phase,type,normalize(message)].join("|"));const now=Date.now(),throttle=readThrottle(),previous=throttle[signature],previousAt=previous?Date.parse(String(previous.lastAt||"")):NaN;if(previous&&Number.isFinite(previousAt)&&now-previousAt<HOUR){previous.count=Number(previous.count||1)+1;previous.lastAt=new Date(now).toISOString();writeThrottle(throttle);spawnWorker();return {sent:false,throttled:true,signature};}const stamp=new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"").replace("T","-");const dir=path.join(rt.dataDir,"diagnostics","pending");fs.mkdirSync(dir,{recursive:true});const filename=`AssistantPlanning-Diagnostic-${stamp}-${process.pid}-${Math.random().toString(16).slice(2,8)}.zip`;const report={version:String(info.version||""),build:String(info.build||""),installationId:installationId(),date:new Date().toISOString(),module,phase,action,type,error:message,lastProgress:redact(readJsonFile(rt.dataPath("sync-progress.json"))),locks:lockState(),connectionState:connectionState(),repeatCount:1,signature};zipFiles(filesForReport(report),path.join(dir,filename));throttle[signature]={lastAt:new Date(now).toISOString(),count:1,pending:filename};writeThrottle(throttle);spawnWorker();return {sent:false,pending:filename,signature};}catch{return {sent:false,error:"diagnostic_creation_failed"};}}
function flushPending(){spawnWorker();}
module.exports={redact,safeMessage,normalize,reportError,flushPending,zipFiles,readThrottle,shouldReport};
if(require.main===module&&process.argv.includes("--csharp-error")){try{const encoded=process.argv[process.argv.indexOf("--csharp-error")+1]||"";const payload=JSON.parse(Buffer.from(encoded,"base64").toString("utf8"));reportError(payload);}catch{}}
