"use strict";
const fs=require("fs"),path=require("path"),crypto=require("crypto"),runtime=require("./runtime-config"),{google}=require("googleapis");
function config(){try{return runtime.parseJson(fs.readFileSync(path.join(__dirname,"diagnostic-config.json"),"utf8"));}catch{return {};}}
function b64(value){return Buffer.from(value).toString("base64").replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");}
function safe(value){return String(value||"").replace(/(?:access[_ -]?token|refresh[_ -]?token|client[_ -]?secret|password|cookie|authorization|bearer|code_verifier|oauth.?code)\s*[:=]?\s*[^\s,;]*/ig,"[REDACTED]").slice(0,1000);}
function lock(){const file=runtime.dataPath("diagnostic-send.lock");try{const fd=fs.openSync(file,"wx");return [fd,file];}catch{return null;}}
function rawMail(from,to,report,attachment){const boundary="=_AssistantPlanningDiagnostic_"+crypto.randomBytes(8).toString("hex");const subject=`⚠️ Assistant Planning — Erreur automatique — v${report.version||"inconnue"}`;const body=[`Version : ${report.version||"inconnue"}`,`PC : ${report.installationId||"anonymisé"}`,`Date : ${report.date||new Date().toISOString()}`,`Étape : ${report.phase||"inconnue"}`,`Action : ${report.action||"inconnue"}`,`Erreur : ${safe(report.error)}`,`Dernière progression : ${report.lastProgress&&report.lastProgress.percent!=null?report.lastProgress.percent+" %":"inconnue"}`,"","Le rapport détaillé est joint. Les valeurs sensibles ont été masquées."].join("\r\n");const headers=[`From: ${from}`,`To: ${to}`,`Subject: =?UTF-8?B?${Buffer.from(subject,"utf8").toString("base64")}?=`,`MIME-Version: 1.0`,`Content-Type: multipart/mixed; boundary="${boundary}"`].join("\r\n");return b64(headers+"\r\n\r\n--"+boundary+"\r\nContent-Type: text/plain; charset=UTF-8\r\nContent-Transfer-Encoding: 8bit\r\n\r\n"+body+"\r\n\r\n--"+boundary+"\r\nContent-Type: application/zip; name=\""+attachment.name+"\"\r\nContent-Disposition: attachment; filename=\""+attachment.name+"\"\r\nContent-Transfer-Encoding: base64\r\n\r\n"+attachment.data.toString("base64").match(/.{1,76}/g).join("\r\n")+"\r\n--"+boundary+"--\r\n");}
function readReport(zip){try{const zlib=require("zlib"),nameLen=zip.readUInt16LE(26),extraLen=zip.readUInt16LE(28),size=zip.readUInt32LE(18),start=30+nameLen+extraLen,body=zip.subarray(start,start+size),text=(zip.readUInt16LE(8)===8?zlib.inflateRawSync(body):body).toString("utf8");return JSON.parse(text.replace(/^\uFEFF/,""));}catch{return {};}}
async function sendOne(file,auth,email){const zip=fs.readFileSync(file),report=readReport(zip);const raw=rawMail(email,config().supportEmail,report,{name:path.basename(file),data:zip});const gmail=google.gmail({version:"v1",auth});await gmail.users.messages.send({userId:"me",requestBody:{raw}});try{fs.unlinkSync(file);}catch{}return true;}
async function main(){runtime.initialize();const cfg=config(),support=String(cfg.supportEmail||"").trim();if(!/^\S+@\S+\.\S+$/.test(support))return;if(!runtime.hasSecret("google-token"))return;const guard=lock();if(!guard)return;try{const {auth}=await require("./google-oauth-v2").authorizedClient();const email=String((await google.oauth2({version:"v2",auth}).userinfo.get()).data?.email||"").trim();if(!/^\S+@\S+\.\S+$/.test(email))return;const dir=path.join(runtime.dataDir,"diagnostics","pending");if(!fs.existsSync(dir))return;for(const name of fs.readdirSync(dir).filter(x=>x.toLowerCase().endsWith(".zip")).slice(0,3)){try{await sendOne(path.join(dir,name),auth,email);}catch{break;}}try{runtime.writeJson("diagnostic-status.json",{status:"sent",at:new Date().toISOString()});}catch{} }catch{try{runtime.writeJson("diagnostic-status.json",{status:"pending",at:new Date().toISOString()});}catch{}}finally{try{fs.closeSync(guard[0]);fs.unlinkSync(guard[1]);}catch{}}}
if(require.main===module)main().catch(()=>{});
else module.exports={main};
