"use strict";
const http=require("http"),crypto=require("crypto");
const {spawn}=require("child_process");
const {google}=require("googleapis");
const rt=require("./runtime-config");
function config(){
 const x=rt.readProgramJson("google-oauth-config.json",{}),id=String(x.clientId||"").trim();
 if(!id)throw new Error("OAuth Google non configure par le distributeur.");
 return {clientId:id,clientSecret:"",scopes:Array.isArray(x.scopes)&&x.scopes.length?x.scopes.map(String):["https://www.googleapis.com/auth/calendar.app.created","https://www.googleapis.com/auth/calendar.calendarlist.readonly"],calendarSummary:String(x.calendarSummary||"SDIS-BOT"),calendarMarker:String(x.calendarMarker||"[SDIS-BOT]")};
}
function isConfigured(){try{config();return true}catch{return false;}}
function openBrowser(url){const p=spawn("rundll32.exe",["url.dll,FileProtocolHandler",url],{detached:true,windowsHide:true,stdio:"ignore"});p.unref();}
function waitCode(server,state){return new Promise((resolve,reject)=>{let done=false;const timer=setTimeout(()=>finish(new Error("Autorisation Google expiree.")),300000);function finish(e,v){if(done)return;done=true;clearTimeout(timer);try{server.close();}catch{}e?reject(e):resolve(v);}server.on("request",(req,res)=>{try{const u=new URL(req.url,"http://127.0.0.1");if(u.pathname!=="/oauth2callback"){res.writeHead(404);res.end();return;}if(u.searchParams.get("state")!==state){res.writeHead(400);res.end();finish(new Error("Reponse OAuth invalide."));return;}if(u.searchParams.get("error")){res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});res.end("<h1>Connexion annulee</h1>");finish(new Error("Autorisation Google annulee."));return;}const code=u.searchParams.get("code");if(!code){res.writeHead(400);res.end();finish(new Error("Code Google absent."));return;}res.writeHead(200,{"Content-Type":"text/html; charset=utf-8"});res.end("<h1>Connexion reussie</h1><p>Vous pouvez fermer cette fenetre.</p>");finish(null,code);}catch(e){finish(e);}});});}
async function listCalendars(api){const out=[];let pageToken;do{const r=await api.calendarList.list({minAccessRole:"writer",showDeleted:false,maxResults:250,pageToken});out.push(...(r.data.items||[]));pageToken=r.data.nextPageToken;}while(pageToken);return out;}
async function ensureCalendar(auth,cfg,allowCreate){const api=google.calendar({version:"v3",auth}),saved=rt.readJson("google-calendar.json",{});if(saved.calendarId){try{await api.calendars.get({calendarId:saved.calendarId});return {calendarId:saved.calendarId,created:false,pendingCreate:false};}catch{}}
 const existing=(await listCalendars(api)).find(x=>String(x.summary||"").trim()===cfg.calendarSummary||String(x.description||"").includes(cfg.calendarMarker));
 if(existing&&existing.id){rt.writeJson("google-calendar.json",{calendarId:existing.id,summary:existing.summary});return {calendarId:existing.id,created:false,pendingCreate:false};}
 if(!allowCreate)return {calendarId:"",created:false,pendingCreate:true};
 const created=await api.calendars.insert({requestBody:{summary:cfg.calendarSummary,description:`${cfg.calendarMarker} Calendrier gere par SDIS-BOT`,timeZone:"Europe/Paris"}});rt.writeJson("google-calendar.json",{calendarId:created.data.id,summary:created.data.summary});return {calendarId:created.data.id,created:true,pendingCreate:false};}
async function connectGoogle(){rt.initialize();const cfg=config(),server=http.createServer();await new Promise((resolve,reject)=>server.listen(0,"127.0.0.1",resolve).on("error",reject));const port=server.address().port,redirect=`http://127.0.0.1:${port}/oauth2callback`,auth=new google.auth.OAuth2(cfg.clientId,cfg.clientSecret,redirect),state=crypto.randomBytes(32).toString("hex");openBrowser(auth.generateAuthUrl({access_type:"offline",prompt:"consent",include_granted_scopes:true,scope:cfg.scopes,state}));const code=await waitCode(server,state),tokens=(await auth.getToken(code)).tokens;if(!tokens.refresh_token&&rt.hasSecret("google-token"))tokens.refresh_token=rt.token().refresh_token;if(!tokens.refresh_token)throw new Error("Google n'a pas fourni le renouvellement. Reconnecter Google.");auth.setCredentials(tokens);rt.saveSecret("google-token",JSON.stringify(tokens));const dry=rt.readJson("dendreo-config.json",{dryRun:true}).dryRun;return ensureCalendar(auth,cfg,!dry);}
async function authorizedClient(){const cfg=config();if(!rt.hasSecret("google-token"))throw new Error("Reconnecter Google.");const auth=new google.auth.OAuth2(cfg.clientId,"","http://127.0.0.1");try{auth.setCredentials(rt.token());}catch{throw new Error("Reconnecter Google.");}rt.bindGoogleAuth(auth);return {auth,cfg};}
async function status(){if(!isConfigured())return {configured:false,connected:false,reconnect:true};const connected=rt.hasSecret("google-token"),saved=rt.readJson("google-calendar.json",{});return {configured:true,connected,reconnect:!connected,calendarId:saved.calendarId||""};}
module.exports=require("./google-oauth-v2");
