"use strict";
const fs=require("fs"),path=require("path"),os=require("os"),https=require("https"),crypto=require("crypto");
const {spawn}=require("child_process");
const rt=require("./runtime-config");
function log(result,message){try{fs.mkdirSync(rt.dataDir,{recursive:true});fs.appendFileSync(rt.dataPath("assistant-planning.log"),`[${new Date().toLocaleTimeString("fr-FR")}] [UPDATE] ${result} - ${String(message||"").replace(/[\r\n]+/g," ").slice(0,500)}\n`,"utf8");}catch{}}
let progressState={},progressWritten=0;
function report(options,event){progressState={...progressState,...event,updatedAt:new Date().toISOString()};const now=Date.now();if(!event.downloaded||now-progressWritten>=300||event.downloaded===event.total){try{rt.writeJson("update-progress.json",progressState);progressWritten=now;}catch{}}try{options&&options.progress&&options.progress(event);}catch{}}
function version(){try{return String(rt.readProgramJson("app-version.json",{}).version||"0.0.0");}catch{return "0.0.0";}}
function compare(a,b){const x=String(a).split(".").map(Number),y=String(b).split(".").map(Number);for(let i=0;i<3;i++)if((x[i]||0)!==(y[i]||0))return (x[i]||0)>(y[i]||0)?1:-1;return 0;}
function config(){return rt.readProgramJson("update-config.json",{});}
function response(url,timeout,redirects=0){return new Promise((resolve,reject)=>{
 let address;try{address=new URL(url);if(address.protocol!=="https:")throw new Error("Lien de mise à jour non sécurisé.");}catch(e){reject(e);return;}
 const req=https.get(address,{timeout,headers:{"User-Agent":"Assistant-Planning-Updater"}},res=>{
  if([301,302,303,307,308].includes(res.statusCode)){
   res.resume();
   if(!res.headers.location||redirects>=8){reject(new Error("Redirection de mise à jour invalide."));return;}
   let target;try{target=new URL(res.headers.location,address).href;}catch(e){reject(e);return;}
   response(target,timeout,redirects+1).then(resolve,reject);return;
  }
  if(res.statusCode!==200){res.resume();reject(new Error("HTTP "+res.statusCode));return;}
  resolve(res);
 });
 req.on("timeout",()=>req.destroy(new Error("Délai de mise à jour dépassé."))).on("error",reject);
});}
async function fetchJson(url){const res=await response(url,10000);let body="";for await(const chunk of res){body+=chunk.toString("utf8");if(Buffer.byteLength(body,"utf8")>1048576)throw new Error("Manifest trop volumineux.");}return rt.parseJson(body);}
async function check(){const current=version(),url=String(config().manifestUrl||"").trim();if(!/^https:\/\//i.test(url))return {available:false,currentVersion:current};try{const m=await fetchJson(url),app=m.app||{},target=String(m.version||app.version||""),downloadUrl=String(app.url||""),sha256=String(app.sha256||"").toLowerCase(),size=Number(app.size||0)||null;const available=compare(target,current)>0&&/^https:\/\//i.test(downloadUrl)&&/^[a-f0-9]{64}$/.test(sha256);return {available,currentVersion:current,version:available?target:current,downloadUrl:available?downloadUrl:"",sha256:available?sha256:"",size:available?size:null};}catch(e){log("ERREUR",e.message);return {available:false,currentVersion:current,temporary:true};}}
function sha256(file){return new Promise((resolve,reject)=>{const h=crypto.createHash("sha256");fs.createReadStream(file).on("data",x=>h.update(x)).on("error",reject).on("end",()=>resolve(h.digest("hex")));});}
async function download(url,target,options={}){
 const res=await response(url,60000);let n=0,total=Number(res.headers["content-length"]||0)||null;
 res.on("data",chunk=>{n+=chunk.length;report(options,{stage:"Téléchargement du package complet",downloaded:n,total});});
 try{await require("stream/promises").pipeline(res,fs.createWriteStream(target));if(total!==null&&n!==total)throw new Error("Téléchargement incomplet.");}
 catch(error){try{fs.unlinkSync(target);}catch{}throw error;}
}
function pidAlive(pid){try{process.kill(Number(pid),0);return true;}catch(e){return e&&e.code==="EPERM";}}
function lockActive(file){if(!fs.existsSync(file))return false;let active=false;try{const meta=JSON.parse(fs.readFileSync(file,"utf8"));active=pidAlive(meta.pid);}catch{}if(active)return true;try{fs.unlinkSync(file);return false;}catch{throw new Error("Ancien verrou de mise à jour impossible à supprimer.");}}
function updateInProgress(){return lockActive(rt.dataPath("update.lock"));}
function acquireLock(file){fs.mkdirSync(path.dirname(file),{recursive:true});if(lockActive(file))throw new Error("Mise à jour déjà en cours.");const fd=fs.openSync(file,"wx");fs.writeFileSync(fd,JSON.stringify({pid:process.pid,date:new Date().toISOString(),type:"update"}),"utf8");return fd;}
function winQuote(value){const s=String(value);return '"'+s.replace(/(\\*)"/g,'$1$1\\"').replace(/(\\*)$/,'$1$1')+'"';}
function launchUpdater(packageFile,lockFile,expected){const temp=fs.mkdtempSync(path.join(os.tmpdir(),"assistant-planning-updater-")),script=path.join(temp,"updater.ps1"),handoff=path.join(temp,"handoff.cmdline");fs.copyFileSync(path.join(__dirname,"update-helper.ps1"),script);const progressScript=path.join(__dirname,"update-progress-window.ps1");if(fs.existsSync(progressScript))fs.copyFileSync(progressScript,path.join(temp,"update-progress-window.ps1"));const logo=path.join(__dirname,"assets","udsp14-logo.png");if(fs.existsSync(logo))fs.copyFileSync(logo,path.join(temp,"udsp14-logo.png"));const ps=path.join(process.env.SystemRoot||"C:\\Windows","System32","WindowsPowerShell","v1.0","powershell.exe"),launcher=path.join(__dirname,"AssistantPlanning-UpdateLauncher.exe");if(!fs.existsSync(launcher))throw new Error("Lanceur de mise à jour absent.");const args=["-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File",script,"-Package",packageFile,"-InstallRoot",__dirname,"-Exe",path.join(__dirname,"SDIS-Collegues.exe"),"-UpdateLock",lockFile,"-ExpectedVersion",expected,"-TempRoot",temp];fs.writeFileSync(handoff,[ps,...args].map(winQuote).join(" "),"utf8");const worker=spawn(launcher,[handoff],{cwd:temp,windowsHide:true,stdio:"ignore"});if(!worker.pid)throw new Error("Le lanceur de mise à jour n'a pas démarré.");let helperPid=0;for(let i=0;i<100;i++){try{helperPid=Number(fs.readFileSync(handoff+".pid","utf8"))||0;}catch{}if(helperPid)break;Atomics.wait(new Int32Array(new SharedArrayBuffer(4)),0,0,50);}if(!helperPid){let code="";try{code=fs.readFileSync(handoff+".error","utf8").trim();}catch{}throw new Error("Le helper de mise à jour n'a pas démarré"+(code?" (Windows "+code+")":"")+".");}fs.writeFileSync(lockFile,JSON.stringify({pid:helperPid,date:new Date().toISOString(),type:"update"}),"utf8");worker.once("error",error=>{try{fs.unlinkSync(lockFile);}catch{}log("ERREUR",error.message);});worker.unref();}
async function install(info,options={}){if(!info)info=await check();if(!info.available)throw new Error(info.temporary?"Mise à jour indisponible":"Aucune mise à jour disponible.");const lock=rt.dataPath("update.lock");let fd,temp="";try{fd=acquireLock(lock);progressState={};temp=fs.mkdtempSync(path.join(os.tmpdir(),"assistant-planning-download-"));const pkg=path.join(temp,"AssistantPlanning-app.zip");report(options,{stage:"Nouvelle version détectée",version:info.version,currentVersion:info.currentVersion});await download(info.downloadUrl,pkg,options);report(options,{stage:"V\u00e9rification du t\u00e9l\u00e9chargement",downloaded:undefined,total:undefined});const actual=(await sha256(pkg)).toLowerCase();if(actual!==info.sha256)throw new Error("SHA-256 du package invalide.");log("OK","SHA-256 valide pour "+info.version);report(options,{stage:"SHA-256 valide",percent:100});report(options,{stage:"Installation : Assistant Planning va red\u00e9marrer",percent:100});launchUpdater(pkg,lock,info.version);log("OK","updater temporaire lancé");setTimeout(()=>process.exit(0),250);return {ok:true,started:true,usedDelta:false};}catch(e){if(fd!==undefined){try{fs.closeSync(fd);fd=undefined;fs.unlinkSync(lock);}catch{}}report(options,{stage:"Mise \u00e0 jour interrompue",error:e.message});log("ERREUR",e.message);throw e;}finally{try{if(fd!==undefined)fs.closeSync(fd);}catch{}if(temp){try{setTimeout(()=>fs.rmSync(temp,{recursive:true,force:true}),30000);}catch{}}}}
module.exports={version,check,install,compare,sha256,fetchJson,download,updateInProgress};
